stages:
  - test

test-py310:
   image: python:3.10
   stage: test
   coverage: '/\d+\%$/'
   script:
     - apt-get update
     - apt-get -y install unixodbc-dev
     - python setup.py install
     - pip install -r requirements-dev.txt
     - pip install --upgrade git+https://github.com/TeskaLabs/asab.git#egg=asab
     - coverage run -m unittest test
     - coverage report -m

test-py38:
  image: python:3.8
  stage: test
  coverage: '/\d+\%$/'
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - python setup.py install
    - pip install -r requirements-dev.txt
    - pip install --upgrade git+https://github.com/TeskaLabs/asab.git#egg=asab
    - coverage run -m unittest test
    - coverage report -m

flake8:
  image: python:3.10
  stage: test
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - python setup.py install
    - pip install -r requirements-dev.txt
    - pip install --upgrade git+https://github.com/TeskaLabs/asab.git#egg=asab
    - pip install flake8
    - flake8 bspump
