variables:
  DOCKER_REGISTRY: 201508596767.dkr.ecr.eu-central-1.amazonaws.com
  AWS_DEFAULT_REGION: eu-central-1
  DOCKER_HOST: tcp://docker:2375

stages:
  - test

test-py310:
  image: python:3.10
  stage: test
  coverage: '/\d+\%$/'
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - pip3 install --upgrade cython
    - pip3 install .
    - pip install -r requirements-dev.txt
    - coverage run -m unittest test
    - coverage report -m

flake8:
  image: python:3.10
  stage: test
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - pip3 install --upgrade cython
    - pip3 install .
    - pip install -r requirements-dev.txt
    - flake8 bspump

publish-base-image:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  variables:
    AWS_REGION: eu-central-1
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/bspump:$CI_PIPELINE_IID .
    - docker tag $DOCKER_REGISTRY/bspump:$CI_PIPELINE_IID $DOCKER_REGISTRY/bspump:latest
    - docker push $DOCKER_REGISTRY/bspump:$CI_PIPELINE_IID
    - docker push $DOCKER_REGISTRY/bspump:latest

