variables:
  DOCKER_REGISTRY: public.ecr.aws/h9w9d7v3
  AWS_DEFAULT_REGION: us-east-1
  DOCKER_HOST: tcp://docker:2375

stages:
  - test

test-py310:
  image: python:3.10
  stage: test
  coverage: '/\d+\%$/'
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - pip3 install --upgrade cython
    - pip3 install .
    - pip install -r requirements-dev.txt
    - coverage run -m unittest test
    - coverage report -m

flake8:
  image: python:3.10
  stage: test
  script:
    - apt-get update
    - apt-get -y install unixodbc-dev
    - pip3 install --upgrade cython
    - pip3 install .
    - pip install -r requirements-dev.txt
    - flake8 bspump

publish-base-image:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - yum install git
    - aws --version
    - docker --version
  script:
    - YEAR=$(date +%Y)
    - COMMIT_HASH=$(git rev-parse --short HEAD)
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/bspump:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH .
    - docker tag $DOCKER_REGISTRY/bspump:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH $DOCKER_REGISTRY/bspump:latest
    - docker push $DOCKER_REGISTRY/bspump:latest
    - docker push $DOCKER_REGISTRY/bspump:$YEAR-$CI_PIPELINE_IID-git-$COMMIT_HASH
